# this is bash config file. variables assigned in bash formal will be read and usable by focusmode.sh

allowed_to_operate=1
update_frequency=5

websites=("www.tumblr.com" "www.youtube.com" "www.theguardian.com")


